on: push

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build-examples:
    name: Build examples
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - { ref: 'main',    tag_suffix: '',         os: 'windows-latest', compiler: 'msvc' }
          - { ref: 'docking', tag_suffix: '-docking', os: 'windows-latest', compiler: 'msvc' }
          - { ref: 'main',    tag_suffix: '',         os: 'ubuntu-latest',  compiler: 'gcc' }
          - { ref: 'docking', tag_suffix: '-docking', os: 'ubuntu-latest',  compiler: 'gcc' }
          - { ref: 'main',    tag_suffix: '',         os: 'ubuntu-latest',  compiler: 'clang' }
          - { ref: 'docking', tag_suffix: '-docking', os: 'ubuntu-latest',  compiler: 'clang' }

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ matrix.ref }}

      - name: Checkout imgui with the latest version
        working-directory: cimgui
        run: git clone --depth 1 --branch $(gh release list -R ocornut/imgui --limit 1 --json tagName --jq '.[0].tagName')${{ matrix.tag_suffix }} https://github.com/ocornut/imgui.git

      - name: Install build dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y xorg-dev libwayland-dev libltdl-dev

      - name: Install build dependencies (Ubuntu + GCC)
        if: matrix.os == 'ubuntu-latest' && matrix.compiler == 'gcc'
        uses: ./.github/actions/build-gcc-15

      - name: Install build dependencies (Ubuntu + Clang)
        if: matrix.os == 'ubuntu-latest' && matrix.compiler == 'clang'
        run: sudo apt-get install -y libc++-dev libc++abi-dev

      - name: Enable Developer Command Prompt (Windows + MSVC)
        if: matrix.os == 'windows-latest' && matrix.compiler == 'msvc'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake and Build
        if: matrix.os != 'ubuntu-latest' || matrix.compiler != 'gcc'
        run: |
          mv .github/workflows/scripts/* examples
          cd examples
          cmake --preset=${{ matrix.os }}-${{ matrix.compiler }}
          cmake --build build --config Release

      - name: Configure CMake and Build (Ubuntu + GCC)
        if: matrix.os == 'ubuntu-latest' && matrix.compiler == 'gcc'
        run: |
          mv .github/workflows/scripts/* examples
          cd examples
          wget https://github.com/Kitware/CMake/releases/download/v4.1.2/cmake-4.1.2-linux-x86_64.tar.gz
          tar -xf cmake-4.1.2-linux-x86_64.tar.gz
          cmake-4.1.2-linux-x86_64/bin/cmake --preset=${{ matrix.os }}-${{ matrix.compiler }}
          cmake-4.1.2-linux-x86_64/bin/cmake --build build --config Release